export const copy = {
  title: 'Slopeyballs',
  blurb: 'A single-player ribbon run. Grip, launch, and bring the cluster home.',
  tips: [
    'Hold to grip the ribbon. Speed builds as it falls away.',
    'Release on the rise to launch. Hold in the air to dive.',
  ],
  gates: 'Mint arches add orbs. Gold arches multiply. Coral arches take orbs.',
  play: 'Run',
  workshop: 'Workshop',
  back: 'Back',
  retry: 'Retry',
  next: 'Next course',
  home: 'Home',
  cleared: 'Cluster home',
  failed: 'Cluster lost',
  last: 'That was the last course.',
  orbs: 'orbs',
  coins: 'coins',
  open: 'Open',
  best: 'Best haul',
  noneYet: 'No haul on this course yet.',
  banked: 'Coins banked',
  newBest: 'New best haul.',
  grip: 'Grip',
  air: 'Air',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  looks: 'Looks',
  use: 'Use',
  using: 'Using',
  maxed: 'Max',
  buy: 'Buy',
  upgrades: {
    cluster: { name: 'Cluster', detail: 'More orbs at the start of a run.' },
    glide: { name: 'Glide', detail: 'Higher launches and a slower fall.' },
    purse: { name: 'Purse', detail: 'Courses pay more coins.' },
  },
}
